data:
  path: "data/Student_Stress_Factors.csv"
  target_column: "How would you rate your stress levels?"  # Nombre original del CSV
  test_size: 0.2
  random_state: 42

model:
  type: "RandomForest"
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42

mlflow:
  experiment_name: "student-stress-prediction"
  tracking_uri: "file:./mlruns"
  run_name: "rf_baseline"